version: '3'

networks:
    laravel:

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: mysql
        ports:
            - "8080:80"
        networks: 
            - laravel
    redis:
        image: redis:alpine
        container_name: redis
        command: redis-server --appendonly yes --requirepass secret
        volumes:
            - ./redis:/data
        ports:
            - "6379:6379"
        networks:
            - laravel
    